//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjEstacionamento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro
    {
        public System.DateTime AnoFabricacao { get; set; }
        public System.DateTime AnoModelo { get; set; }
        public string Cor { get; set; }
        public int Id { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
    }
}
