//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjEstacionamento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacionamento
    {
        public System.DateTime DataEntrada { get; set; }
        public System.DateTime DataSaida { get; set; }
        public string Descricao { get; set; }
        public int Id { get; set; }
        public string NomeCliente { get; set; }
        public string Telefone { get; set; }
        public double Valor { get; set; }
    }
}
